**Table of contents**<a id='toc0_'></a>    
- [Introduction to Tensors](#toc1_)    
- [Creating Tensors](#toc2_)    
  - [From List](#toc2_1_)    
    - [Checking Tensor Types](#toc2_1_1_)    
  - [From Numpy](#toc2_2_)    
    - [Bridged Memory](#toc2_2_1_)    
- [Arithmatic Operations](#toc3_)    
  - [Point-wise operations](#toc3_1_)    
    - [Addition / Sub](#toc3_1_1_)    
    - [Multiplication / Division](#toc3_1_2_)    
    - [Abs](#toc3_1_3_)    
    - [Transpose](#toc3_1_4_)    
  - [Matric Multiplication](#toc3_2_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Introduction to Tensors](#toc0_)
Tensors are building blocks for deep learning models. Tensors are used to represent vectors and scalars

In [1]:
import torch

# <a id='toc2_'></a>[Creating Tensors](#toc0_)
## <a id='toc2_1_'></a>[From List](#toc0_)

In [5]:
a = torch.tensor([1])
b = torch.tensor([1.,2,3])
c = torch.tensor([[1,2,3],[2,3,4],[3,4,5]])

In [3]:
a,b,c

(tensor([1]),
 tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]))

### <a id='toc2_1_1_'></a>[Checking Tensor Types](#toc0_)

In [6]:
a.dtype, b.dtype

(torch.int64, torch.float32)

## <a id='toc2_2_'></a>[From Numpy](#toc0_)
Numpy as one of heavily used libraries for number manipulation and torch provides easy way to interchange data between numpy and torch

In [7]:
import numpy as np
a = np.array([1,2,3.])
b = torch.from_numpy(a)

In [8]:
a, b

(array([1., 2., 3.]), tensor([1., 2., 3.], dtype=torch.float64))

### <a id='toc2_2_1_'></a>[Bridged Memory](#toc0_)
Once we create tensor from numpy, the memory location is shared between numpy and torch instances. If we make changes in any of these variables, other variable also highlights the effect

In [9]:
a += 1

In [10]:
a, b

(array([2., 3., 4.]), tensor([2., 3., 4.], dtype=torch.float64))

# <a id='toc3_'></a>[Arithmatic Operations](#toc0_)
## <a id='toc3_1_'></a>[Point-wise operations](#toc0_)
### <a id='toc3_1_1_'></a>[Addition / Sub](#toc0_)

In [17]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,3,4])
print(a + b)
print(a-b)

tensor([3, 5, 7])
tensor([-1, -1, -1])


### <a id='toc3_1_2_'></a>[Multiplication / Division](#toc0_)

In [19]:
print(a * b)
print(b / a)

tensor([ 2,  6, 12])
tensor([2.0000, 1.5000, 1.3333])


### <a id='toc3_1_3_'></a>[Abs](#toc0_)

In [22]:
print(abs(-8))

8


### <a id='toc3_1_4_'></a>[Transpose](#toc0_)

In [32]:
a , b

(tensor([1, 2, 3]), tensor([2, 3, 4]))

In [33]:
a.t()

tensor([1, 2, 3])

In [34]:
a = torch.tensor([[1,2,3], [4,5,6]])
print(a)
print(a.t())

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## <a id='toc3_2_'></a>[Matric Multiplication](#toc0_)

In [42]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,3,4])
print( a * b) # point wise multiplication

tensor([ 2,  6, 12])


In [43]:
print(a @ b)
print(a.t() @ b)
print(a @ b.t())

tensor(20)
tensor(20)
tensor(20)


In [44]:
a = torch.tensor([[1,2,3], [4,5,6]])
print(a @ b)

tensor([20, 47])


In [46]:
print(a @ b.t())

tensor([20, 47])


In [45]:
print(a.t() @ b)

RuntimeError: size mismatch, got 3, 3x2,3